### ISSUE TITLE
Is translation case-sensitive?

### ISSUE THREAD

**Issue by stefan-reich** [apertium/apertium-all#4]
Hi,

apertium_de2en("ohr") => "ohr"
apertium_de2en("Ohr") => "Ear"

I mean... really?

Please advise

**Comment by TinoDidriksen** [comment]
Yes, generally translation is case-sensitive because languages are case-sensitive. Especially German where nouns are capitalized. 'ohr' is not a word, but 'Ohr' is.

The adage of "garbage in, garbage out" applies. Any error in the input will be amplified in the translation chain. It is very important that the input is correct.

We can create heuristics, and something like German nouns is a classic case where it might help, but it's up to the language/pair developers how much garbage they want to take guesses at.
